---
$schema: "https://json-schema.org/draft/2020-12/schema"

description: vdb_16S annotate config schema

type: object

properties:
  # inputs
  pool:
    type: string
  asv_fasta:
    type: string
  adapter_ref:
    type: string
  human_ref:
    type: string
  mouse_ref:
    type: string
  anno_db:
    type: string

  # run parameters
  skip_contam_search:
    type: boolean
    default: true

required:
  - pool
  - asv_fasta
  - adapter_ref
  - human_ref
  - mouse_ref
  - anno_db
