# annotation databases
# see https://github.com/vdblab/resources
adapter_ref: /data/brinkvd/resources/references/synthetic/stephenturner-adapters/93b5f91/adapters_combined_256_unique.fasta
human_ref: /data/brinkvd/resources/indexes/human/CHM13/v2.0/minimap2/chm13v2.0.fa.gz.mmi
mouse_ref: /data/brinkvd/resources/indexes/mouse/GRCm39/GCA_000001635.9/minimap2/GCA_000001635.9_GRCm39_genomic.fna.gz.mmi
anno_db: /data/brinkvd/resources/dbs/ncbi16S/2022/16S_ribosomal_RNA_id_and_taxonomy.txt

lib_layout: "paired"
preprocess_min_read_length: 150

# these defaults are taken from dada2
dada2_truncQ: 2
dada2_truncLen: 0
dada2_trimLeft: 0
dada2_trimRight: 0
dada2_maxLen: 0
dada2_minLen: 20
dada2_maxN: 0
dada2_minQ: 0
dada2_rm.lowcomplex: 0
dada2_rm.phix: True
# these are not the defaults
dada2_maxEE: 2
trunclen_R1: 200
trunclen_R2: 180
min_asv_len: 300
nshards: 4

# this requires ~18GB memory, so this is disableable for testing
skip_contam_search: false

# Dont have DB access?
skip_db_upload: false

# Autoexcluder parameters
min_retained: 0.3
min_read_pairs: 200
max_perc_adapter: 5
skip_anno: false
pooling: "none"
removeprimers: true
stage: preprocess
