---
$schema: "https://json-schema.org/draft/2020-12/schema"

description: vdb_16S demux config schema

type: object

properties:
  # inputs
  pool:
    type: string
  oligos:
    type: string
  R1:
    type: array
    items:
      type: string
    minItems: 1
    uniqueItems: true
  R2:
    type: array
    items:
      type: string
    minItems: 1
    uniqueItems: true

  # run parameters
  nshards:
    type: integer
    minimum: 1
    default: 1

required:
  - pool
  - oligos
  - R1
  - R2
