---
$schema: "https://json-schema.org/draft/2020-12/schema"

description: vdb_16S manifest record schema

type: object

properties:
  sample_id:
    type: string
  R1:
    type: string
  R2:
    type: string

required:
  - sample_id
  - R1
