---
name: Run Full Integration Test
env:
  TMPDIR: /tmp/

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: snakemake/snakemake:v7.31.1
      options: --privileged  --workdir /github/workspace --rm -e TMPDIR
      volumes:
        - /github/workspace/:/github/workspace/
    name: Test Pipelines
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test amplicon demux
        run: >
          echo `pwd` && snakemake
          --directory .test_results/
          --cores 1
          --jobs 1
          --resources "mem_mb=5000"
          --use-singularity
          --singularity-prefix /github/workspace/.singularity/
          --singularity-args '-B /github/,/__w/'
          --config
          stage=demux
          pool=test
          nshards=2
          R1=["$PWD/.test/amplicon/test_input/test_R1_001.fastq.gz"]
          R2=["$PWD/.test/amplicon/test_input/test_R2_001.fastq.gz"]
          oligos=$PWD/.test/amplicon/test_input/pool1059.oligos
